apiVersion: apps/v1
Kind: Deployment
metadata:
  name: nginx-Deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blood-bank
  template:
    metadata:
      labels:
        app: blood-bank
    spec:
      containers:
      - name: app
        image: rammohan855/blood-bank:appimage
        ports:
        - containerPort: 80
        env:
          - name: DB_HOST
            value: mysqldb
      imagePullSecrets:
        - name: mysecret
        